packages:
  - upstream/web
  - upstream/packages/*
  - config
  - branding
  - custom
  - overrides
  - "@parcel/watcher"

preferWorkspacePackages: true
injectWorkspacePackages: true
verifyDepsBeforeRun: false
