packages:
  - upstream/web
  - upstream/packages/*
  - config
  - branding
  - custom
  - overrides
  - "@parcel/watcher"

preferWorkspacePackages: true
injectWorkspacePackages: true
verifyDepsBeforeRun: false
allowBuilds:
  '@parcel/watcher': true
  canvas: true
  es5-ext: true
  esbuild: true
  sharp: true
